server:
  port: 8080
spring:
  application:
    name: spring-greeting-service-with-config-in-yml
management:
  endpoints:
    web:
      exposure:
        include:
        - 'env'
        - 'beans'
        #- '*'
        # https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html
greeting-service:
  greeting : "Olá"
  default-value : "mundo - seu lindo!"
  